version: "3"
services:
  selenium-chrome:
    image: selenium/standalone-chrome:117.0-chromedriver-117.0
    ports:
      - "4444:4444"  # selenium本体
      - "7900:7900"  # VNC http://127.0.0.1:7900/?autoconnect=1&resize=scale&password=secret
    shm_size: 2gb
